sudo: false
language: python
python:
  - 2.7

# command to install dependencies
before_install:
  - mkdir $HOME/.aws
  - cp ./tests/config $HOME/.aws

cache:
  directories:
    - $HOME/.cache/pip
install:
  - pip install pip --upgrade
  - pip install -r requirements/develop.txt
  - pip install -e .

# command to run tests
script: python setup.py test
