sudo: false
language: python
python:
  - 2.7

# command to install dependencies
before_install:
  - mkdir $HOME/.aws
#  - cp ./tests/config $HOME/.aws

install:
  - pip install pip --upgrade
  - pip install -r requirements/develop.txt
  - "python setup.py install"

# command to run tests
script: py.test .
